[package]
name = "solana-tower-defense"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
bevy-inspector-egui = "0.29.1"
bevy_ecs_tiled = "0.5.1"
bevy_ecs_tilemap = "0.15.0"
rand = "0.9.0"
solana-client = "2.2.2"
solana-sdk = "2.2.1"
toml-cfg = "0.2.0"
